target "zenrus" do
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    pod 'AFNetworking', '~> 3.0'
    pod 'MagicalRecord'
    pod 'XMLDictionary'
    pod 'SVPullToRefresh'
end